export const INCREMENT_CONTROL = 'INCREMENT_CONTROL';
export type INCREMENT_CONTROL = typeof INCREMENT_CONTROL;

export const DECREMENT_CONTROL = 'DECREMENT_CONTROL';
export type DECREMENT_CONTROL = typeof DECREMENT_CONTROL;
