// Global action constants

// MQTT action constants
export const MQTT_CLIENT_CONNECTING = 'MQTT_CLIENT_CONNECTING';
export type MQTT_CLIENT_CONNECTING = typeof MQTT_CLIENT_CONNECTING;

export const MQTT_CLIENT_CONNECTED = 'MQTT_CLIENT_CONNECTED';
export type MQTT_CLIENT_CONNECTED = typeof MQTT_CLIENT_CONNECTING;

export const MQTT_CLIENT_CONNECTION_FAILED = 'MQTT_CLIENT_CONNECTION_FAILED';
export type MQTT_CLIENT_CONNECTION_FAILED = typeof MQTT_CLIENT_CONNECTION_FAILED;

export const INCREMENT_CONTROL = 'INCREMENT_CONTROL';
export type INCREMENT_CONTROL = typeof INCREMENT_CONTROL;

export const DECREMENT_CONTROL = 'DECREMENT_CONTROL';
export type DECREMENT_CONTROL = typeof DECREMENT_CONTROL;

export const ENABLE_CONTROL = 'ENABLE_CONTROL';
export type ENABLE_CONTROL = typeof ENABLE_CONTROL;

export const DISABLE_CONTROL = 'DISABLE_CONTROL';
export type DISABLE_CONTROL = typeof DISABLE_CONTROL
;
export const ADD_SERVER_CONFIG = 'ADD_SERVER_CONFIG';
export type ADD_SERVER_CONFIG = typeof ADD_SERVER_CONFIG;